steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build',
         '-t',
         'gcr.io/my-project/my-image',
         '.',
         '-f',
         'splendor_sim/continous_intergration/DockerPytestCI.docker']
  timeout: 600s
